development:
      key:    "801078737"
      secret: "d8cf504891096c77e920178ae32afc67"
      url:    "http://www.ssg.com"
      callback: "http://localhost:3000/syncs/qq/callback"
production:
      key:    "801078737"
      secret: "d8cf504891096c77e920178ae32afc67"
      url:    "http://boluo.me"
      callback: "http://boluo.me/syncs/qq/callback"

