development:
      key:    "3788831273"
      secret: "cd9072acaac30aaa6d7a45dc8fff57e3"
      url:    "boluo.me"
      callback: "http://localhost:3000/syncs/sina/callback"
production:
      key:    "3788831273"
      secret: "cd9072acaac30aaa6d7a45dc8fff57e3"
      url:    "boluo.me"
      callback: "http://boluo.me/syncs/sina/callback"

