# config/mongo.yml

defaults: &defaults
  host: 127.0.0.1
  port: 27017

development:
  <<: *defaults
  database: ssg
  autocreate_indexes: true

test:
  <<: *defaults
  database: ssg_test
  autocreate_indexes: true

# set these environment variables on your prod server
# host: staff.mongohq.com #  port: 10082 #  host: ds029187.mongolab.com #  port: 29187
production:
  host: 127.0.0.1
  port: 27017
  database: heroku_app3550586
  username: boluome
  password: ssg_boluome
